### ISSUE TITLE
Building custom genome data

### ISSUE THREAD

**Issue by wuwill** [kundajelab/chipseq_pipeline#11]
Are there any instructions on how to build custom genome data for a species that is not available for the pipeline? What are the usual resources to find relevant data, like the black list, ATAC specific annotation data?

**Comment by akundaje** [comment]
https://github.com/kundajelab/chipseq_pipeline#genome-data

**Comment by akundaje** [comment]
Oh sorry. You want to install new species.

Jin - Didnt we have some documentation on how to add new species?

-A

**Comment by leepc12** [comment]
Please refer to the section "Installer for genome data" on
https://kundajelab.github.io/bds_pipeline_modules/programming.html.

I also added it to README on the pipeline git repo.

Thanks,

Jin

**Comment by wuwill** [comment]
Thank you, Dr. Kundaje and Jin. This is helpful.

I guess I can use the installer to add new species based on $REF_RA. At the
same time, I am wondering where are the common sources to find information
on the BLACKLIST / TSS_ENRICH / DNASE / ROADMAP_META, etc. To be specific,
I want to add data for "D. melanogaster" (dm3). I noticed the installer
points to files on UCSC and mitra.stanford.edu. It is not clear to me know
to get files like those that are retrieved from mitra.stanford.edu. I know
it is problem not something you do, but any suggestion would be greatly
appreciated.

Thanks,
Will

**Comment by leepc12** [comment]
Please get the latest pipeline. I added dm3 to the genome database
installer. Also, I simplied customization for genome database installer.

We currently don't have BLACKLIST for dm3. Just leave it blank. Peaks will
not be filtered.

Please ignore TSS_ENRICH / DNASE / ROADMAP_META. Those are for atac seq
pipeline.

Thanks,

Jin

**Comment by wuwill** [comment]
Jin,

Thank you for the fast update. it worked. However, I am actually adding
this species for an ATAC-seq run. Do you think the pipeline still works
without the ATAC annotation data? I am running a first-pass data quality
check with one sample for now. Eventually, we want to have more samples and
need the extra annotation information.

BTW, I want to thank you for the great job building and updating the
ATAC-seq pipeline. I got some great results for a mouse data a few weeks
earlier. Really appreciate it.

Thanks,
Will

**Comment by leepc12** [comment]
Sure. The ATAC-Seq pipeline can run without ATAQC genome database. There
will be no ATAQC analysis based on annotation data, but you will still get
mapped bams and peaks.

Thanks,

Jin

**Comment by wuwill** [comment]
Great. Thank you! -Will
