### ISSUE TITLE
Installing Genomes: TwoBitToFa not found

### ISSUE THREAD

**Issue by AHCChan** [kundajelab/chipseq_pipeline#13]
Hi!

I installed the pipeline then tried to install a genome but came across this

`install_genome_data.sh: line 171: twoBitToFa: command not found`

I tried to install twobittofa using conda but ran into some issues. Is there any workaround?

**Comment by leepc12** [comment]
Hello,

Did you follow the installation instruction for dependencies (
https://github.com/kundajelab/chipseq_pipeline#dependencies)? twoBitToFa is
included in that.

It is not recommended to manually install dependencies. It's very tricky.
The pipeline needs two conda environments for each python version 2/3 and
some required softwares are not available on official conda repos.

Please use the dependency installer in the repo.

Thanks,

Jin

**Comment by AHCChan** [comment]
Hello,

Yes, I followed the installation instructions and used the dependency installer (install_dependencies.sh). I received a message saying that the dependency installation was successful

`Finished processing dependencies for idr==2.0.3
== Installing dependencies has been successfully done. ==`

For good measure, I uninstalled the dependencies and ran the dependency installation script again. I still get the same error when trying to install a genome.

`install_genome_data.sh: line 171: twoBitToFa: command not found`


Many thanks,

Angelo

**Comment by leepc12** [comment]
It's fixed. Please try with the latest code.

**Comment by AHCChan** [comment]
Hi, sorry to bother you again. I tried with the new code and received this message:

`Extracting/processing data files...
Building bwa index...
[bwa_index] Pack FASTA... 47.76 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=5451530962, availableWord=395589816
[BWTIncConstructFromPacked] 10 iterations done. 99999986 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 199999986 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 299999986 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 399999986 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 499999986 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 599999986 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 699999986 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 799999986 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 899999986 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 999999986 characters processed.
install_genome_data.sh: line 221: 20197 Killed                  bwa index ${REF_FA_PREFIX}`

**Comment by leepc12** [comment]
Did you run the installer script on a login node (if you are working on a cluster)? Does your computer have enough memory to run bwa index?
