### ISSUE TITLE
How to modify bds if my SGE cluster using vf=memory,p=n_cpu?

### ISSUE THREAD

**Issue by huboqiang** [kundajelab/chipseq_pipeline#16]
Hi

I succeed in submitting my jobs using this pipeline. However, I found the resource claimed in bds.config does not work so the pipeline would run even if my cluster is full of jobs.  My SGE cluster used `vf=memory,p=n_cpu` instead of `h_vmem` and `slots`. We used to submit jobs like:

```
qsub -cwd -l vf=10g,p=8 -V run.sh
```

In my `bds.config`, I used:

```
sge.pe = make
sge.mem = vf
sge.timeout = h_rt
sge.timeout2 = s_rt
clusterRunAdditionalArgs = -V
```

The question is how could I modify my config file to adding something like `vf=10g,p=8` in `qsub` command? Thank you.

**Comment by leepc12** [comment]
BDS only works with SGE PE (parallel environment). You may need to ask your
admin to make a PE for the pipeline. Please see "SGE cluster options" in
https://pcingola.github.io/BigDataScript/bigDataScript_manual.html for
details.

Jin

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
