### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by biomystery** [kundajelab/chipseq_pipeline#18]

**Comment by leepc12** [comment]
Please remove all version specification (==*) in requirements.txt and try
again.

Jin

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
