### ISSUE TITLE
SPP error in one replicate

### ISSUE THREAD

**Issue by dgoekbuget** [kundajelab/chipseq_pipeline#22]
Hi,
when I run your pipeline with 2 treatment and 2 control conditions, I get the following error after supposably several attempts to run SPP on a rep2 (see below).

Do you have an idea why? Thanks for helping out.

| 9116 | running (RUNNING) | spp rep2  |              | if [ $(which run_spp_nodups.R 2> /dev/null | wc -l || echo) == "1" ]; then RUN_SPP=$(which run_spp_nodups.R);; else RUN_SPP=$(which run_spp.R);; fi; Rscript  ${RUN_SPP} -c=data/align/rep2/n-flag-n2.nodup.tagAlign.gz -p=1 -i=/ | 

03:48:51.697	Writing report file 'chipseq.bds.20171126_120808_625.report.html'
There were 23 warnings (use warnings() to see them)
data/krishnakumar2016/chipseq.bds.20171126_120808_625/task.callpeak_spp.spp_rep2.line_68.id_18.sh: line 38: error_in_spp_output_peak_does_not_exist: command not found
Task failed:
	Program & line     : 'TF_chipseq_pipeline/modules/callpeak_spp.bds', line 68
	Task Name          : 'spp rep2'
	Task ID            : 'chipseq.bds.20171126_120808_625/task.callpeak_spp.spp_rep2.line_68.id_18'
	Task PID           : '9116'
	Task hint          : 'if [ $(which run_spp_nodups.R 2> /dev/null | wc -l || echo) == "1" ]; then RUN_SPP=$(which run_spp_nodups.R);; else RUN_SPP=$(which run_spp.R);; fi; Rscript  ${RUN_SPP} -c=data/align/rep2/n-flag-n2.nodup.tagAlign.gz -p=1 -i=/'
	Task resources     : 'cpus: -1	mem: -1.0 B	wall-timeout: 8640000'
	State              : 'ERROR'
	Dependency state   : 'ERROR'
	Retries available  : '1'
	Input files        : '[data/align/rep2/n-flag-n2.nodup.tagAlign.gz, data/align/ctl2/n-ctr-n2.nodup.tagAlign.gz]'
	Output files       : '[data/peak/spp/rep2/n-flag-n2.nodup.tagAlign_x_n-ctr-n2.nodup.tagAlign.regionPeak.gz, data/peak/spp/rep2/n-flag-n2.nodup.tagAlign_x_n-ctr-n2.nodup.tagAlign.ccscore, data/peak/spp/rep2/n-flag-n2.nodup.tagAlign_x_n-ctr-n2.nodup.tagAlign.pdf]'
	Script file        : 'data/chipseq.bds.20171126_120808_625/task.callpeak_spp.spp_rep2.line_68.id_18.sh'
	Exit status        : '1'
	Program            :

**Comment by leepc12** [comment]
Can you post a full log here or send me via email (leepc12 at gmail dt
com)? Also, please run the following commands for debugging info (out/ is
your -out_dir).

$ ls -l out/peak/spp/rep*
$ ls -l out/qc/rep*
$ cat out/qc/rep*/*.cc.qc

JIn

**Comment by leepc12** [comment]
closing this due to long inactivity
