### ISSUE TITLE
permission denied / file not found

### ISSUE THREAD

**Issue by michdass** [kundajelab/chipseq_pipeline#23]
Hey,

I installed everything according to your instructions without noticing any errors, but I cannot get chipseq.py to work. If I use fastq or bam as input, I get an error of the following form

fork/exec /media/nico/data/home2/projects/macrophages/chip_ana2/8-ENCODE-pipeline/chipseq.bds.20171207_115700_844/task.postalign_bam.dedup_bam_1_rep1.line_155.id_10.sh: permission denied

If I use peaks as input, the error has the following form: 
Error (/home/nico/TF_chipseq_pipeline/modules/input_peak.bds, line 31, pos 33): 		File not found!
The files pass the initial check, though.

I don't know what to do next.

Here is the stderr output when running with a fastq and with a peak input. 

[log-17_12_07-11:56:57.txt](https://github.com/kundajelab/chipseq_pipeline/files/1538790/log-17_12_07-11.56.57.txt)

[log-17_12_07-11:54:38.txt](https://github.com/kundajelab/chipseq_pipeline/files/1538791/log-17_12_07-11.54.38.txt)

**Comment by leepc12** [comment]
Please check permission for directories and files on your pipeline output
directory (`/media/nico/data/home2/projects/macrophages`).

Jin

**Comment by michdass** [comment]
the directory is drwxrwxr-x
and the files are -rw-rw-r--
the bam files are even -rwxrwxrwx

**Comment by leepc12** [comment]
What about pipeline's repo directory (`chipseq_pipeline/`)?

**Comment by michdass** [comment]
TF_chipseq_pipeline/ has drwxrwxr-x as well. I'm assuming the Aquas-Pipeline directory does not have to be put into a specific place? It's right now in my home directory. 

 

 

 

 

 

 

Gesendet: Samstag, 09. Dezember 2017 um 19:21 Uhr
Von: "Jin Lee" <notifications@github.com>
An: kundajelab/chipseq_pipeline <chipseq_pipeline@noreply.github.com>
Cc: michdass <nico.barth@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [kundajelab/chipseq_pipeline] permission denied / file not found (#23)


What about pipeline's repo directory (chipseq_pipeline/)?

**Comment by leepc12** [comment]
I am sorry for long delay.

Permissions on the pipeline source directory looks okay, but I suspect that
you still have a permission issue on your output directories. Our pipeline
makes many temporary files and directories under your working directory
(it's not -out_dir but where you run the pipeline command line). Does your
cluster limit file/dir permission on your working directories?

Please run the following command lines and post outputs here.

$ touch /media/nico/data/home2/projects/macrophages/chip_
ana2/8-ENCODE-pipeline/file_permission_test

$ mkdir /media/nico/data/home2/projects/macrophages/chip_
ana2/8-ENCODE-pipeline/dir_permission_test
$ touch /media/nico/data/home2/projects/macrophages/chip_
ana2/8-ENCODE-pipeline/dir_permission_test/file_permission_test

Thanks,

Jin

**Comment by michdass** [comment]
Hey Jin,

currently I am trying to set up the pipeline on my local machine, not on a cluster. So there shouldn't be any permission restrictions in the output or working directories. Those commands are executed without any errors. 

Thanks,
Nico

**Comment by leepc12** [comment]
Can you try installing pipeline on your /home/$USERID/chipseq_pipelines?
How is your output directory mounted to the system?

$ df -h /media/nico/data/home2/projects/macrophages/chip_ana2

Jin

**Comment by michdass** [comment]
The pipeline was installed in my home directory before, I re-downloaded it and reinstalled the dependencies and the genome data, but I still get the same errors.

df output:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1       1.8T  1.5T  242G  87% /media/nico/data

**Comment by leepc12** [comment]
Did you have enough disk space on /tmp, $TMP and $TMPDIR? What is your $TMP
and $TMPDIR?

echo $TMP
echo $TMPDIR
df -h $TMP
df -h $TMPDIR
df -h /tmp

Jin

**Comment by michdass** [comment]
Currently I indeed do not have a lot of space on my main drive. 

df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        86G   76G  5.1G  94% /

$TMP and $TMPDIR are not defined.

I cannot make more than 15 GB available on the main drive currently, but I could define a temporary directory on another drive if that doesn't suffice.

**Comment by leepc12** [comment]
You will need at least 30GB in your /tmp for the pipeline. Subtasks in the
pipeline sometimes make very large temporary BAM files.

Jin
