### ISSUE TITLE
aquas_chipseq pipline idr error

### ISSUE THREAD

**Issue by adroubsa** [kundajelab/chipseq_pipeline#30]
Hello 

could you kindly help me to fix an error i keep getting when running aquas_chipseq pipeline , the error jam getting is as below:

00:16:53.803	Wait: Waiting for task to finish: chipseq.bds.20180325_124007_960/task.callpeak_idr.idr2_rep1_pr.line_80.id_36, state: ERROR
Task failed:
	Program & line     : '/home/adroubsa/TF_chipseq_pipeline/modules/callpeak_idr.bds', line 80
	Task Name          : 'idr2 rep1-pr'
	Task ID            : 'chipseq.bds.20180325_124007_960/task.callpeak_idr.idr2_rep1_pr.line_80.id_36'
	Task PID           : '41355'
	Task hint          : 'idr --samples /scratch/dragon/intel/adroubsa/HDAC2_Chip_Seq_DMD/HDAC_T6_DMD/DMD_T6_HDAC2_sam_files/HDAC2_DMD_T6_Chip_Seq_analysis/peak/macs2/pseudo_reps/rep1/pr1/D9813_T6_HDAC2_merged_Rep1.nodup.pr1.tagAlign_x_D9813_T6_HDAC2_Input1.nodup.tagAlign.pval0.01.500K.narrowPeak.gz /scratch/dragon/intel/adr'
	Task resources     : 'cpus: -1	mem: -1.0 B	wall-timeout: 8640000'
	State              : 'ERROR'
	Dependency state   : 'ERROR'
	Retries available  : '1'

your kind help is much appreciated

**Comment by leepc12** [comment]
@adroubsa I need more info for debugging. Please post a full log.

**Comment by adroubsa** [comment]
Dear Jin

Kindly find attached the full log file , i have changed the html report file to txt file to be able to upload it .

i checked the number of peaks in rep1-rep2- idr thresholded  and its 0 ( no peaks ) could that be the reason . 
also some of the finished tasks in the html report has [i] , what does it mean

[chipseq.bds.20180403_212245_923.report.txt.gz](https://github.com/kundajelab/chipseq_pipeline/files/1879252/chipseq.bds.20180403_212245_923.report.txt.gz)

Thanks again in advance

**Comment by leepc12** [comment]
closing this due to long inactivity
