### ISSUE TITLE
Read length

### ISSUE THREAD

**Issue by jloupe** [kundajelab/chipseq_pipeline#33]
We have been using the Aquas pipeline successfully with 75bp SE reads. However, our sequencing core is adding NovaSeq machines that will at minimum give 100bp reads. Is there an advantage/disadvantage to the extra read length? Will we need to change anything in the pipeline to adjust for this difference?

Thank you in advance!

**Comment by akundaje** [comment]
No change. The pipeline will work just fine.

**Comment by jloupe** [comment]
That's great, thank you for the quick response!
