### ISSUE TITLE
[fread] Unexpected end of file (bwa_sai2sam_pe_core)

### ISSUE THREAD

**Issue by sbstatgen** [kundajelab/chipseq_pipeline#38]
I am getting the following error for a paired end chipseq data.
.
.
.
[bwa_read_seq] 2.6% bases are trimmed.
                [bwa_read_seq] 1.8% bases are trimmed.
                [bwa_sai2sam_pe_core] convert to sequence coordinate...
                [fread] Unexpected end of file

00:18:26.669    Wait: Task 'chipseq.bds.20180516_143724_219_parallel_30/task.align_bwa.bwa_sam_PE_ctl1.line_181.id_10' finished.
Fatal error: /path/TF_chipseq_pipeline/modules/align_bwa.bds, line 87, pos 3. Task/s failed.

I checked that the fastq files (i.e. for both replicate and control replicate, i checked the pairing of reads, between read1 and read2, it looks ok).

Interestingly this error is coming at the end of aligning a control replicate. The same control replicate I have used as control for a different replicate. There the whole pipeline ran till completion.  How do I fix this? Thanks in advance...

**Comment by leepc12** [comment]
Please search for the error on the internet before posting an issue.
https://www.biostars.org/p/186585/

Do `ls -l` on the genome data directory for bwa index and .fa file. Also please post a full log.

**Comment by sbstatgen** [comment]
I am attaching the full nohup output and error files (I was not aware of the attach option, have just started using github). This time I ran with 1 replicate and 1 control replicate and got same error.


Regarding the biostars thread, it turns out that I had gone through this and some other biostars posts for a few days before I posted the issue. Accordingly I had checked my fastq files for pairing of reads. This is why I mentioned in my original post that 
"**I checked that the fastq files (i.e. for both replicate and control replicate, i checked the pairing of reads, between read1 and read2, it looks ok).**"
To be specific I checked all sequences are of same length (100) and all read1 and read2-ID-s are paired correctly. I may still be missing something in that biostars thread, please point it out (it happens that I am sort of new to sequencing analysis and terminology).

Regarding, the genome-data folder I had come across that suggestion somewhere and checked that it has all the files ".fa", ".fai", and bwa_index has amb, ann, bwt, pac and sa files. Pasting the "ls -l" here
 
sb1@sb-hpz800:bwa_index $ ls -l
total 5290524
lrwxrwxrwx 1 sb1 sb1         15 Apr 10 10:23 male.hg19.fa -> ../male.hg19.fa
-rw-rw-r-- 1 sb1 sb1       6548 Apr 10 11:10 male.hg19.fa.amb
-rw-rw-r-- 1 sb1 sb1        944 Apr 10 11:10 male.hg19.fa.ann
-rw-rw-r-- 1 sb1 sb1 3095694072 Apr 10 11:10 male.hg19.fa.bwt
-rw-rw-r-- 1 sb1 sb1  773923497 Apr 10 11:10 male.hg19.fa.pac
-rw-rw-r-- 1 sb1 sb1 1547847040 Apr 10 11:24 male.hg19.fa.sa

sb1@sb-hpz800:hg19 $ ls -l
total 3997972
drwxr-xr-x 2 sb1 root       4096 Apr  9 17:04 ataqc
drwxrwxr-x 2 sb1 sb1        4096 Apr 10 11:24 bwa_index
-rw-rw-r-- 1 sb1 sb1         376 Apr 10 10:23 hg19.chrom.sizes
-rw-rw-r-- 1 sb1 sb1  3157608038 Apr 10 10:19 male.hg19.fa
-rw-rw-r-- 1 sb1 sb1         788 Apr 10 10:23 male.hg19.fa.fai
-rw-r--r-- 1 sb1 root  936272240 Jan 28  2010 male.hg19.fa.gz
drwxr-xr-x 2 sb1 root       4096 Apr 10 10:23 seq
-rw-r--r-- 1 sb1 root       4731 May  5  2011 wgEncodeDacMapabilityConsensusExcludable.bed.gz

Oh and at the end of the run I am getting valid T0L1R1.PE2SE.sam.gz file. It looks complete but no sam file or any sai is seen for the second read R2. For rep1, I get all files including bam, tagAlign etc for read 1, but nothing for read 2.

Please suggest how I can go about debugging this. Thanks again for patiently reading all this.



[eT4.txt](https://github.com/kundajelab/chipseq_pipeline/files/2029544/eT4.txt)
[oT4.txt](https://github.com/kundajelab/chipseq_pipeline/files/2029582/oT4.txt)

**Comment by sbstatgen** [comment]
Both $TMP and $TMPDIR are null (undefined) in my bash shell. But since the other replicates have run successfully, I guess that is not a problem.

I am using a single blade server, sometimes also a workstation (same error in both). On the server
MemTotal:       65774440 kB
MemFree:        48467220 kB
MemAvailable:   52434928 kB

There may be 1 or 2 other users running jobs occasionally (not in my control). On the workstation, I am the only user.

MemTotal:       24671836 kB
MemFree:        21266696 kB

As you suggested I tried mem_bwa 30G on the server and got the same error. What should be the number of threads "nth" ?  This is lscpu on the server and workstation.

Server
CPU(s):                6
Thread(s) per core:    1
Core(s) per socket:    6

Workstation

CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6

Another suspicion I have is that for this replicate somehow wall time is being crossed after creating .sai for 1'st read. I am trying this now with nth=8  on the server:

               "wt_bwa" : "71h",
                "mem_bwa" : "30G",

Is there any way to skip the index already done for read1 and proceed to read 2 ?

**Comment by sbstatgen** [comment]
Sorry it seems there are two unrelated issues here. I discovered that although my other runs were completed without error, they only gave files for R1 (read 1). This one had probably failed because of memory or storage or wall time issue. I am running with higher memory etc as you suggested and it has gone closer to completion (not yet completed). so i will close this issue. the primary issue now is why it is only taking the read1's separately. so i will probably post the issue with a different heading. thanks.

**Comment by leepc12** [comment]
FYI, read1 (R1) fastq is separately processed (as single ended) for cross-correlation analysis only and it's not used for other downstream analyses like peak calling and IR.
