### ISSUE TITLE
Missing `-c` for `macs2 peakcall` ? 

### ISSUE THREAD

**Issue by Avsecz** [kundajelab/chipseq_pipeline#42]
Seems that `-c` is missing between `$tag` and `$ctl`
https://github.com/kundajelab/chipseq_pipeline/blob/master/modules/callpeak_macs2_chipseq.bds#L188

```bash
sys macs2 callpeak -t $tag $ctl -f BED -n $prefix.tmp \
	-g $gensz -p $pval_thresh_macs2 --broad --nomodel --shift $shift_macs2 $extsize_param \
	--keep-dup $keep_dup_macs2 $extra_param_macs2
```

Encode pipeline description has the `-c`: https://docs.google.com/document/d/1lG_Rd7fnYgRpSIqrIfuVlAz2dW1VaSQThzk836Db99c/edit#

```bash
macs2 callpeak -t ${REP1_TA_FILE}.tagAlign.gz -c ${CONTROL_TA_PREFIX}.tagAlign.gz -f BED -n ${PEAK_OUTPUT_DIR}/${CHIP_TA_PREFIX} -g ${GENOMESIZE} -p 1e-2 --nomodel --shift 0 --extsize ${FRAGLEN} --keep-dup all -B --SPMR
```

**Comment by leepc12** [comment]
`$ctl` is a BDS variable which already includes `-c`.
https://github.com/kundajelab/chipseq_pipeline/blob/master/modules/callpeak_macs2_chipseq.bds#L74
```
ctl 	:= (ctl_tag != "") ? "-c $ctl_tag" : ""
```
