### ISSUE TITLE
pipeline deprecated?

### ISSUE THREAD

**Issue by ceesu** [kundajelab/chipseq_pipeline#43]
Hello,

Thanks for making this software available. 

I have been using the current version of chipseq_pipeline for the past few months and would like to continue using it. However, last week I noticed that the readme.md has the message 'This pipeline has been deprecated'. 
I took a quick look at the new version of the pipeline, it seems that the steps are largely the same though the installation is different. Does this sound correct?

Thanks!

**Comment by leepc12** [comment]
Yes, that's correct. But you need to install dependencies with new `install_dependencies.sh`.

**Comment by ceesu** [comment]
Okay, thank you.
