### ISSUE TITLE
Some reps get ERROR:root:--extsize must >= 1!

### ISSUE THREAD

**Issue by jloupe** [kundajelab/chipseq_pipeline#45]
We have run several ChIP-seq datasets through the Aquas pipeline, and occasionally we will get ERROR:root:--extsize must >= 1!
It will cause any rep with this error to fail.
What causes this error and what can be done to correct it?

I have found that if the pipeline shows this error, we can change the macs2 --extsize parameter to 200, and restart the job. The pipeline will pick up from macs2 and apparently complete the job without error. The resulting output seems to be correct when looking at the number of peaks called, passing IDR, and visualizing bigwigs with IGV. However, the cross-correlation plot is clearly effected and the estimated fragment length is negative. Is this the correct or best way to address this issue?

I have attached the output log from such a run, along with the summary html and an example image of bigwig visualization between reps. Rep1 ran normally, Rep2 had the error.
Thanks.

[DEAF1_CB_Output_report.pdf](https://github.com/kundajelab/chipseq_pipeline/files/2444273/DEAF1_CB_Output_report.pdf)
<img width="1468" alt="screen shot 2018-10-03 at 2 50 35 pm" src="https://user-images.githubusercontent.com/37379607/46443475-5e0d7580-c733-11e8-966d-a860f7949245.png">
[DEAF1_CB_pipeline.json.log](https://github.com/kundajelab/chipseq_pipeline/files/2444275/DEAF1_CB_pipeline.json.log)

**Comment by akundaje** [comment]
Yes occasionally the fragment length estimation fails for some datasets
which have weak fragment length peaks in the cross-correlation. In such a
case you can set the fragment length explicitly to something like 150-200
and rerun the pipeline. So what you did is absolutely fine.

-Anshul.

**Comment by jloupe** [comment]
Thank you very much for the response.
