### ISSUE TITLE
Documentation for macs2?

### ISSUE THREAD

**Issue by concatenize** [kundajelab/chipseq_pipeline#46]
This pipeline allows for use of macs2 in peak calling, but in the googledoc, I can't find what parameters are used. What parameters are given to macs2 for peak calling? Thanks!

**Comment by leepc12** [comment]
You can find it in the chapter 6 of this document.

https://docs.google.com/document/d/1lG_Rd7fnYgRpSIqrIfuVlAz2dW1VaSQThzk836Db99c/edit?usp=sharing

**Comment by concatenize** [comment]
Thanks! I had only looked in the section on "peak calling".
