### ISSUE TITLE
Citing the AQUAS Pipeline

### ISSUE THREAD

**Issue by mkleyman** [kundajelab/chipseq_pipeline#47]
Hello,

I used the AQUAS TF Chip-seq peak calling pipeline for a work that I will be submitting very soon and I can't find which DOI to officially cite in the paper? Which DOI  is the best to associate with the pipeline?

-Michael

**Comment by akundaje** [comment]
Please cite the GitHub URL and this paper 
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3431496/
