### ISSUE TITLE
Fatal error: /data/fmao/soft/chipseq_pipeline/modules/graphviz.bds, line 126, pos 18. Trying to access element number 1 from list 'etc' (list size: 1).

### ISSUE THREAD

**Issue by maofengbiao** [kundajelab/chipseq_pipeline#9]
Final parameter values: [0.86 1.24 0.53 0.01]
Number of reported peaks - 24706/24706 (100.0%)

Number of peaks passing IDR cutoff of 0.05 - 7/24706 (0.0%)

Task has finished (119 seconds).
62944 (process ID) old priority 0, new priority 0
Task has finished (0 seconds).

== Done do_idr()
63010 (process ID) old priority 0, new priority 0
63265 (process ID) old priority 0, new priority 0
Fatal error: /data/fmao/soft/chipseq_pipeline/modules/graphviz.bds, line 126, pos 18. Trying to access element number 1 from list 'etc' (list size: 1).
chipseq.bds, line 67 :  main()
chipseq.bds, line 70 :  void main() { // chipseq pipeline starts here
chipseq.bds, line 92 :          report()
chipseq.bds, line 1204 :        void report() {
chipseq.bds, line 1211 :                html += html_graph()            // graphviz workflow diagram
graphviz.bds, line 83 : string html_graph() { // graph diagram
graphviz.bds, line 90 :         dot := _make_dot("$rpt_aux_dir/$prefix"+"workflow.dot")
graphviz.bds, line 108 :        string _make_dot( string file ) {
graphviz.bds, line 120 :                for ( int k=0; k<_tmp_in.size(); k++ ) {
graphviz.bds, line 126 :                        box_name := etc[1]

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.

**Comment by leepc12** [comment]
Sorry for late response, can you check your BDS version? You need to install BDS from the forked repo. The official BDS does not work properly with the pipeline.

https://github.com/kundajelab/chipseq_pipeline#bigdatascript
